import { useRef } from 'react';
import type { Photo, PhotoTransform } from '../types/photo';
import { defaultTransform } from '../utils/crop';

export function PhotoEditor({ photo, value, onChange }: { photo: Photo; value: PhotoTransform; onChange: (value: PhotoTransform) => void }) {
  const drag = useRef<{ x: number; y: number; value: PhotoTransform } | null>(null);
  const pointers = useRef(new Map<number, { x: number; y: number }>());
  const pinch = useRef<{ distance: number; scale: number } | null>(null);
  const distance = () => { const [a, b] = [...pointers.current.values()]; return a && b ? Math.hypot(a.x - b.x, a.y - b.y) : 0; };
  return <div className="photo-editor"><p>사진을 드래그하거나 두 손가락으로 확대하세요.</p><div className="zoom"><button onClick={() => onChange({ ...value, scale: Math.max(1, value.scale - .1) })}>−</button><span>확대</span><button onClick={() => onChange({ ...value, scale: Math.min(3, value.scale + .1) })}>＋</button><button className="reset" onClick={() => onChange(defaultTransform)}>초기화</button></div><div className="edit-slot" onPointerDown={event => { pointers.current.set(event.pointerId, { x: event.clientX, y: event.clientY }); event.currentTarget.setPointerCapture(event.pointerId); if (pointers.current.size === 1) drag.current = { x: event.clientX, y: event.clientY, value }; if (pointers.current.size === 2) pinch.current = { distance: distance(), scale: value.scale }; }} onPointerMove={event => { if (!pointers.current.has(event.pointerId)) return; pointers.current.set(event.pointerId, { x: event.clientX, y: event.clientY }); if (pinch.current && pointers.current.size === 2) onChange({ ...value, scale: Math.max(1, Math.min(3, pinch.current.scale * distance() / pinch.current.distance)) }); else if (drag.current) onChange({ ...drag.current.value, offsetX: drag.current.value.offsetX + event.clientX - drag.current.x, offsetY: drag.current.value.offsetY + event.clientY - drag.current.y }); }} onPointerUp={event => { pointers.current.delete(event.pointerId); if (pointers.current.size < 2) pinch.current = null; if (!pointers.current.size) drag.current = null; }} onWheel={event => { event.preventDefault(); onChange({ ...value, scale: Math.max(1, Math.min(3, value.scale + (event.deltaY < 0 ? .1 : -.1))) }); }} onDoubleClick={() => onChange(defaultTransform)}><img src={photo.url} alt="편집 중인 사진" style={{ transform: `translate(${value.offsetX}px,${value.offsetY}px) scale(${value.scale})` }} /></div></div>;
}
